language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
        global:
                - PACKAGE="mirage-xen-ocaml"
                - PINS="mirage-xen-ocaml:. mirage-xen-posix:."
                - REVDEPS="*"
        matrix:
                - OCAML_VERSION=4.04
                - OCAML_VERSION=4.05
                - OCAML_VERSION=4.06
